name: Build and publish
description: Build an publish the docker image for amd64, arm64 and armv7
outputs:
  version:
    description: "The version of the project"
    value: ${{ steps.project-version.outputs.version }}
inputs:
  image-repo:
    required: true
    description: "Repository of the image to build"
  image-tag:
    required: true
    description: "Tag of the image to build"
  dockerhub-delete:
    required: true
    description: "Whether to delete the image from dockerhub after publishing"
  dockerhub-username:
    required: true
    description: "Dockerhub username"
  dockerhub-token:
    required: true
    description: "Dockerhub token"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.4.0"
    - shell: bash
      run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT
      id: project-version
