name: Build and publish
description: Build an publish the docker image for amd64, arm64 and armv7
inputs:
  image-repo:
    required: true
    description: "Repository of the image to build"
  image-tag:
    required: true
    description: "Tag of the image to build"
  dockerhub-delete:
    required: true
    description: "Whether to delete the image from dockerhub after publishing"
  dockerhub-username:
    required: true
    description: "Dockerhub username"
  dockerhub-token:
    required: true
    description: "Dockerhub token"
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: delivery/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: "${{ inputs.image-repo }}:${{ inputs.image-tag }}"

    - name: Delete image if needed
      shell: bash
      run: |
        if [[ ${{ inputs.dockerhub-delete }} == "true" ]]; then
          echo "+Deleting image from dockerhub"
          delivery/scripts/delete-image-dockerhub.sh --repo=${{ inputs.image-repo }} --tag=${{ inputs.image-tag }}
        else
          echo "+Not deleting image from dockerhub (dockerhub-delete=${{ inputs.dockerhub-delete }})"
        fi
      env:
        DOCKERHUB_USERNAME: ${{ inputs.dockerhub-username }}
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
